export interface rightStateRequest {
    userrole: any,
    roleid: string,
    onItemSelect: string,
    mainItemName: any,
    role: any,
    roleprivileges: any,
    _maincheck: boolean,
    _viewcheck: boolean,
    _editcheck: boolean,
    _addcheck: boolean,
    _deletecheck: boolean,
    _detailcheck: boolean,
    show: boolean,
}
