export interface addUserModelRequest {
    selectedFile: string,
      firstname: string,
      firstnameerror: string,
      lastname: string,
      lastnameerror: string,
      email: string,
      emailerror: string,
      mobilenumber: number,
      mobilenumbererror: string,
      password: string,
      passworderror: string,
      checked: boolean,
      selectedFileerror: string,
      onItemSelecterror: string,
      updateTrue: boolean,
      filetrue: boolean,
      file: string,
      userid: number,
      rolename: string,
      type: string,
      isActive: boolean,
      onItemSelect: string,
      userrole:any
}
