export interface roleStateRequest {
    count: string,
    currentPage: string,
    items_per_page: string,
    upperPageBound: number,
    lowerPageBound: number,
    pageBound: number,
    onItemSelect: string,
    userrole: any,
    deleteuserdata:any,
    switchSort: boolean,
    isStatus: boolean,
    _maincheck:boolean,
    deleteFlag:boolean,
}